name: 'Regress Models on Ubuntu'

on:
  # Allows you to run this workflow manually from the Actions tab or through HTTP API
  workflow_dispatch:

jobs:
  sync:
    name: 'Submodules Sync'
    runs-on: ubuntu-latest

    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash

    steps:
    
    - name: Checkout
      uses: actions/checkout@v4
      with:
        repository: HASE-Group/hase_iii_models
        token: ${{ secrets.HASE_III_MODEL_UPDATE }}
        submodules: true
        fetch-depth: 0
        lfs: true
        path: hase_iii_models
        
    - name: Checkout regression tests
      uses: actions/checkout@v4
      with:
        repository: HASE-Group/hase_iii_regression
        token: ${{ secrets.HASE_III_MODEL_UPDATE }}
        submodules: true
        fetch-depth: 0
        lfs: true        
        path: hase_iii_regression

    # Update references
    - name: Git Submodule Update
      run: |
        cd $GITHUB_WORKSPACE/hase_iii_models && git pull --recurse-submodules hase_iii_models
        cd $GITHUB_WORKSPACE/hase_iii_models && git submodule update --remote --recursive hase_iii_models

    - name: Regress
      run : |
        java -jar hase_iii_regression/dist/com.dawdolman.hase.regression.jar $GITHUB_WORKSPACE/hase_iii_models

    #- name: Commit update
    #  run: |
    #    git config --global user.name 'github'
    #    git config --global user.email 'bot@noreply.github.com'
    #    git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
    #    git commit -am "Auto updated submodule references" && git push || echo "No changes to commit"
